version: '3.6'

services:
  service.webthings-gateway:
    build:
      context: service.webthings-gateway
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - 8080:8080
      - 4443:4443
    volumes:
      - ./service.webthings-gateway/data:/home/node/.mozilla-iot
   
  service.prometheus:
    build:
      context: service.prometheus
      dockerfile: Dockerfile
    volumes:
      - ./service.prometheus:/etc/prometheus

  service.tplink-smart-plug:
    build:
      context: service.tplink-smart-plug
      dockerfile: Dockerfile
    ports:
      - 8082:8082

  service.device-discovery:
    build:
      context: service.device-discovery
      dockerfile: Dockerfile
    ports:
      - 8087:8087
    network_mode: host

  service.central-heating:
    build:
      context: service.central-heating
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    env_file:
      - service.central-heating/env.central-heating
  
  service.influxdb:
    build:
      context: service.influxdb
      dockerfile: Dockerfile
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    env_file:
      - service.influxdb/env.influxdb
    volumes:
      - ./service.influxdb/data:/var/lib/influxdb

  service.grafana:
    build:
      context: service.grafana
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    env_file:
      - service.grafana/env.grafana
    user: "1000"
    links:
      - service.influxdb
    volumes:
      - ./service.grafana/data:/var/lib/grafana

  service.telegraf:
    build:
      context: service.telegraf
      dockerfile: Dockerfile
    volumes:
      - ./service.telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./service.grafana/data:/var/lib/grafana

  service.chronograf:
    build:
      context: service.chronograf
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    env_file:
      - service.chronograf/env.chronograf
